package main

const (
	DEFAULT_PRICE  = 500
	FEE_PERCENTAGE = 25

	PRICE_MULTIPLIER          = 1.35
	CANVAS_DURATION           = 60 * 60 * 24
	MAX_COORDINATE_X_PLUS_ONE = 1000
	MAX_COORDINATE_Y_PLUS_ONE = 1000
	PIXELS_PER_ROW            = 50

	PATRON_BONUS_PERCENTAGE_POINTS = 40
	POT_PERCENTAGE_POINTS          = 25

	// number of pixels sold anything may be withdrawn
	WITHDRAW_PIXELS_THRESHOLD = 150000

	REFERRER_PERCENTAGE_POINTS = 8
	// TEAM_PERCENTAGE == 27
	PRECISION_BASE = 1e16
	//TEAM_ACCOUNT = N(ceoimondev11) // todo

	WITHDRAW_QUOTA = 10000000 // 1000 EOS
)
